name: fudgemart_analytics
version: 1.0
config-version: 2

profile: fudgemart_profile

model-paths: ["models"]
target-path: "target"
clean-targets:
  - target
  - dbt_packages

models:
  fudgemart_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
