name: fudgemart_analytics  # Your project name
version: 1.0.0
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

profile: user  # Ensure this matches your dbt Cloud profile name

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fudgemart_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
