version: 2

sources:
  - name: fudgemart
    database: raw
    schema: fudgemart_v3
    tables:
      - name: fm_orders
      - name: fm_order_details
      - name: fm_products
      - name: fm_customers
      - name: fm_vendors
      - name: fm_shipvia_lookup
      - name: fm_employee_timesheets
      - name: fm_employees
      - name: fm_customer_survey
