version: 2
sources:
  - name: fudgemart
    schema: fudgemart_v3
    database: raw
    tables:
      - name: fm_products
        description: "Details about products sold by Fudgemart."
      - name: fm_orders
        description: "Order data for Fudgemart transactions."
      - name: fm_customers
        description: "Customer details for Fudgemart users."
      - name: fm_order_details
        description: "Line item details for each order."
      - name: fm_employees
        description: "Employee information at Fudgemart."
      - name: fm_customer_survey
        description: "Customer survey results."
      - name: fm_creditcards
        description: "Credit card information for transactions."
      - name: fm_customer_creditcards
        description: "Mapping between customers and credit cards."
      - name: fm_customer_product_reviews
        description: "Customer reviews for products."
